version: '3'
services:
  web:
    build: .
    environment:
      PGPASSWORD: platonic-basement-usher-statuary
    ports:
     - "8080:8080"
    links:
     - "db:database"
  db:
    build:
      context: ./db
      dockerfile: Dockerfile
    environment:
      POSTGRES_PASSWORD: platonic-basement-usher-statuary
      POSTGRES_INITDB_ARGS: "-A trust"

